Add reactive multipart request support (WIP)
spring-projects/spring-framework pull request #1201
Opened 2016-10-12 09:24 UTC by sdeleuze

This draft PR is a first Multipart support implementation here for high-level feedbacks and discussion.

It does not include RequestMapping level support, and integration tests do not work yet with Reactor and RxNetty.

2016-10-13 16:23 UTC, sdeleuze commented
I have updated this PR witgh the following changes:
 - Tests now run fine with Reactor Netty and RxNetty
 - `getAllParts()` now caches the resulting mono to allow multiple invocation
 - There is a single `Part` object suitable usable for file and non file parts
 - We now use `Flux.create()` instead of `ReplayProcessor`
 - `NioPart#transferTo()` now uses zero copy  when possible (when a temporary file has been previously created)

@rstoyanchev Could you please make a high-level review of this commit?

2016-10-14 20:19 UTC, rstoyanchev commented
@sdeleuze, apologies for suggesting it but ServerHttpRequest doesn't seem like the right level for exposing multipart support. Having MultipartResolver take ServerHttpRequest as input is already an indication that it's a higher level concern. Then MultipartResolver has to be injected into every request implementation, which is rather repetitive and artificial. It's also a cyclical dependency even at the package level since the http package is logically at a level below the web package and should not depend on anything from it.

It seems to be a better fit for being exposed at the ServerWebExchange level and to avoid a circular dependency again, MultipartResolver and Part should be in server while with maybe a server.multipart sub-package for the implementations. For initialization a MultipartResolver could be a field of HttpWebHandlerAdapter and passed into every created ServerWebExchange. This is very similar to WebSessionManager and WebSession.

For the caching, the cache operator should really be called at construction time or otherwise concurrent calls to getParts can each create a separate pipeline. See how DefaultWebExchange does it for WebSession.

For when the request is not multipart, could we be more lenient and return an empty stream from getParts and a Mono with empty map from getAllParts? It removes the need to check isMultipartRequest first.

Do we need Part.getContentType if we have getHeaders since there are plenty of methods already on part? 

I haven't looked into the implementation library but I presume it is non-blocking indeed? It seems to be returning java.io.InputStream.

2016-10-18 13:49 UTC, sdeleuze commented
No worry indeed, I agree that `ServerHttpRequest` is not the right level to implement that for the reasons you mentioned. I also agree with your remarks on caching and being more lenient if the request is not multipart.

We can remove `Part.getContentType()` since this is just a shortcut to `Part.getHeaders().getContentType()` (with maybe a Javadoc hint to help users for file parts).

Currently I think JSON parts will be natively treated by the underlying library like a part with a `String` based value since it has no filename header. Even if in `NioPart` I allowed to get the content both as a `String` or as a `Publisher<DataBuffer>`, that could be not optimal.

Not sure if that makes sens, but should we add some `HttpMessageReader` based capabilities with some `<T> Flux<T> getContentAsStream(Class<T> type)` and  `<T> Mono<T> getContentAs(Class<T> type)` methods available on `Part` ? Or should we delegate that part to a composite `MultipartHttpMessageReader` that could be initialized with a `List<HttpMessageReader>` like we do on the writing side for SSE?

About the NIO Multipart library, it seems to me that the request parsing is done in a non blocking way but sadly we can only access to data as `String` or `InputStream` depending on the part type, so it may be blocking I suppose. I have implemented an optimisation to be able to perform a zero-copy transfer if the `InputStream` is a `FileInputStream`.

I can take care of the changes discussed here if you are ok.

I am going to create an issue on their GitHub to ask them more insight about the blocking behavior implied by `InputStream` and that fact that non-file part content is only accessible as a String.

2016-10-18 20:20 UTC, rstoyanchev commented
Okay, I'm not too sure what you mean with the HttpMessageReader based capabilities. I would think that Part should only expose basic ways of getting to the data, but once you've updated the PR maybe it will be more clear.

2016-10-19 09:19 UTC, sdeleuze commented
I have pushed an updated PR, and asked [a new question](https://github.com/synchronoss/nio-multipart/issues/4#issuecomment-254652854) to NIO Multipart project lead about how to perform non-blocking processing with their current `InputStream` / `OutputStream` based API.

2016-10-25 21:48 UTC, sdeleuze commented
@rstoyanchev Could you please review the last version of this PR?

2016-10-27 17:03 UTC, rstoyanchev requested changes
Having `ServerWebExchange` to expose multipart methods and delegate to `MultipartResolver` internally looks alright. In fact the MultipartResolver seems to belong in the http package. It's like an HttpMessageReader and could even be used with an HttpMessageReader to further parse the content of a part. I suggest moving `web.multipart.reactive` to `http.reactive` right next to the codec package.

2016-10-27 17:03 UTC, rstoyanchev commented on spring-web/src/main/java/org/springframework/web/multipart/reactive/nio/NioMultipartResolver.java
> +				}
Should this notify the parser about the error which calls `error` on the emitter, so that subscribers for the parts will get the error?

2016-10-27 17:03 UTC, rstoyanchev commented on spring-web/src/main/java/org/springframework/web/multipart/reactive/nio/NioMultipartResolver.java
> +			});
An inner class perhaps given the number of methods?

2016-10-27 17:03 UTC, rstoyanchev commented on spring-web/src/main/java/org/springframework/web/server/ServerWebExchange.java
> +
These could be ordered right below `getPrincipal()` above with `getAllParts` ahead of `getParts` as the more common case. Same for decorator and default implementations.

2016-10-27 17:03 UTC, rstoyanchev commented on spring-web/src/test/java/org/springframework/http/server/reactive/MultipartIntegrationTests.java
> +					})
Could `exchange.getParts()` with `collectToMap` be used to get all parts first and then invoke a method that asserts all parts, which can also be called from `assertGetAllParts`?

2016-10-30 14:35 UTC, sdeleuze commented on spring-web/src/main/java/org/springframework/web/multipart/reactive/nio/NioMultipartResolver.java
> +				});
Reactor `collectMultimap()` is using a `Collection` for the value type while `LinkedMultiValueMap` is taking a `Map<K, List<V>>` parameter, that's why I did not use it in my first implementation, but after more thoughts I was able to use it in my updated commit thanks to `Collectors.toMap()` to change the value type of the map.

2016-10-30 14:37 UTC, sdeleuze commented on spring-web/src/main/java/org/springframework/web/server/ServerWebExchange.java
> +
I changed the order and also proposed new names in order to be more consistent with `getFormData()`: `Mono<MultiValueMap<String, Part>> getFormParts()` and `Flux<Part> getFormPartsAsFlux()`. Are you ok with these new names?

2016-10-30 16:31 UTC, sdeleuze commented
@rstoyanchev  I took in account your feedbacks and:
 - Changed the package to `org.springframework.http.codec.multipart`
 - Polished the Javadoc
 - Renamed `getAllParts()` to `getFormParts()`
 - Renamed `getParts()` to `getFormPartsAsFlux()`
 - Integrated the `MultipartHttpMessageWriter` commit

2017-05-01 18:38 UTC, rstoyanchev commented
This is now in master.

2017-05-01 18:38 UTC, closed without merging