SPR-12031 Support @ContextConfiguration at method level
spring-projects/spring-framework pull request #1255
Opened 2016-12-06 13:35 UTC by fdesu

Prior Spring TestContext Framework wasn't supporting
@ContextConfiguration annotation on a method-level.

This commit enables @ContextConfiguration and
@ContextHierarchy to be the method-level annotations.
Now TCF will emit fully configured throw-away
TestContext for the particular test method.

Issue: SPR-12031

2016-12-12 18:10 UTC, sbrannen requested changes
Please apply the requested changes in order to reduce the amount of noise in this commit.

Thanks!

2016-12-12 18:10 UTC, sbrannen commented on spring-test/src/main/java/org/springframework/test/util/MetaAnnotationUtils.java
> +		if (isAnnotationDeclaredLocally(annotationType, clazz)) {
Production code is not allowed to use static imports.

2016-12-12 20:23 UTC, fdesu commented
@sbrannen 
Can you please advice if [such declaration](https://github.com/spring-projects/spring-framework/pull/1255/files#diff-d8ea9b54580f6b93b075124892369a62R197) permissible. Or should I pull this classes in the _different files_/_into some class as inner classes_. 
Asking because it is forbidden by the Code Style.

2016-12-12 20:55 UTC, sbrannen commented
> Can you please advice if such declarations permitted. Or should I pull this classes in the different files/into some class as inner classes.
> Asking because it is forbidden by the Code Style.

It's definitely forbidden in production code. In test code, I think there are few places where that style is used. But I don't want that in the `spring-test` module. So please convert them to static nested classes within the test class.

Thanks

2016-12-18 14:29 UTC, fdesu commented
@sbrannen 
I amended previous commit and hope that current one is easier to review

2017-06-12 19:02 UTC, closed without merging