Fixed a bug where gradle build would fail on windows.
spring-projects/spring-framework pull request #1358
Opened 2017-03-19 14:15 UTC by Andrei94

Gradle build would fail because of differences of path separators between linux and windows.

2017-03-19 14:15 UTC, pivotal-issuemaster commented
@Andrei94 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1358)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1358) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2017-03-19 14:37 UTC, pivotal-issuemaster commented
@Andrei94 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1358)!

2017-03-22 07:08 UTC, Andrei94 commented
@snicoll review please? :)

2017-03-27 08:15 UTC, snicoll requested changes
There must be a way to define those separator in a non-OS sensible ways. 

Perhaps @sdeleuze knows?

2017-03-27 08:15 UTC, snicoll commented on build.gradle
> +				it.path.endsWith("META-INF\\spring.schemas")
That most certainly broke non-Windows build.

2017-03-27 08:15 UTC, snicoll commented on build.gradle
> +					it.path.endsWith(schemas.get(key).replaceAll('\\/','\\\\'))
Ditto.

2017-03-30 06:57 UTC, Andrei94 commented
@snicoll changes made :smiley:

2017-04-09 07:49 UTC, snicoll commented
@jhoeller you are on Windows right?  Can you check this one please?

2017-04-17 08:33 UTC, Andrei94 commented
@jhoeller any news about this PR?

2017-05-17 20:22 UTC, closed without merging