Timeout Overrides in Messaging Templates
spring-projects/spring-framework pull request #1435
Opened 2017-05-26 17:33 UTC by garyrussell

Issue: SPR-15591

Provide a mechanism to override the configured send and receive timeouts in the
GenericMessagingTemplate.

- overload `doReceive()` to take a receive timeout argument
- for `sendAndReceive()` methods examine message headers for these timeout values
  - remove headers to avoid propagation
  - avoid the unconditional rebuild of the reply message if the original headers weren't present
- also remove headers from simple `send()` operations
- change javadocs for the setters to indicate they are now defaults
- add properties to allow the user to override the header names used
- change `TemporaryReplyChannel` to use the `send` argument and change it to static
  - add package-protected ctor to avoid the compiler creating a synthetic ctor for access

2017-05-26 18:04 UTC, artembilan commented
> JUnit tests should include assert() or fail()

Looks like `ArgumentCaptor` and `assert...` afterwards should be used instead of asserts in the `Answer`

2017-05-26 18:05 UTC, artembilan commented
> JUnit tests should include assert() or fail()

Looks like `ArgumentCaptor` and `assert...` afterwards should be used instead of asserts in the `Answer`

2017-05-26 18:17 UTC, artembilan requested changes
Just a couple concerns from me.

2017-05-26 18:17 UTC, artembilan commented on spring-messaging/src/main/java/org/springframework/messaging/core/GenericMessagingTemplate.java
> +		return sendTimeoutHeader;
` this.` ?

2017-05-26 18:17 UTC, artembilan commented on spring-messaging/src/main/java/org/springframework/messaging/core/GenericMessagingTemplate.java
> +		return receiveTimeoutHeader;
` this.`, too

2017-05-30 21:21 UTC, rstoyanchev commented
This is merged into master as a single commit. Thanks Gary.

2017-05-30 21:21 UTC, closed without merging

2017-05-31 16:06 UTC, garyrussell commented on spring-messaging/src/main/java/org/springframework/messaging/core/GenericMessagingTemplate.java
> +		if (replyMessage != null && (originalReplyChannelHeader!= null || originalErrorChannelHeader != null)) {
@rstoyanchev It turns out this change was incorrect; we need to null-out the channel headers if they were originally null.

Do you want me to submit another PR, or would you mind just reverting this line?

Thanks (and my apologies).

2017-05-31 16:26 UTC, rstoyanchev commented on spring-messaging/src/main/java/org/springframework/messaging/core/GenericMessagingTemplate.java
> +		if (replyMessage != null && (originalReplyChannelHeader!= null || originalErrorChannelHeader != null)) {
If you could push another commit on the same branch, so I can see the exact changes you have in mind.

2017-05-31 16:33 UTC, garyrussell commented on spring-messaging/src/main/java/org/springframework/messaging/core/GenericMessagingTemplate.java
> +		if (replyMessage != null && (originalReplyChannelHeader!= null || originalErrorChannelHeader != null)) {
Sorry - I just issued a new PR on that branch (having first reset it to master).

I issued another PR: https://github.com/spring-projects/spring-framework/pull/1440

Thanks