Add debug logging for CORS rejections
spring-projects/spring-framework pull request #1466
Opened 2017-06-28 01:15 UTC by shorn

Issue: SPR-15708
I have submitted the ICLA.

2017-06-30 07:27 UTC, sdeleuze requested changes
Thanks, could you have a look to my remarks and force push an updated commit.

2017-06-30 07:27 UTC, sdeleuze commented on spring-web/src/main/java/org/springframework/web/cors/DefaultCorsProcessor.java
> +		if (allowOrigin == null) {
To be moved just bellow `checkOrigin` invocation ?

2017-06-30 07:27 UTC, sdeleuze commented on spring-web/src/main/java/org/springframework/web/cors/DefaultCorsProcessor.java
> +		if (allowMethods == null) {
To be moved just bellow `checkMethods` invocation ?

2017-06-30 07:27 UTC, sdeleuze commented on spring-web/src/main/java/org/springframework/web/cors/DefaultCorsProcessor.java
> +		if ((preFlightRequest && allowHeaders == null)) {
To be moved just bellow `checkHeaders` invocation ?

2017-06-30 07:27 UTC, sdeleuze commented on spring-web/src/main/java/org/springframework/web/cors/DefaultCorsProcessor.java
> +			logger.debug("rejecting request because CORS processor cannot determine " +
What about a message like `"Rejecting CORS request because '" + requestOrigin + "' origin is not allowed"`

2017-06-30 07:27 UTC, sdeleuze commented on spring-web/src/main/java/org/springframework/web/cors/DefaultCorsProcessor.java
> +			logger.debug("rejecting request because CORS processor cannot determine " +
Similar remark than for origin for the message

2017-06-30 07:27 UTC, sdeleuze commented on spring-web/src/main/java/org/springframework/web/cors/DefaultCorsProcessor.java
> +			logger.debug("rejecting request because CORS processor cannot determine " +
Similar remark than for origin for the message

2017-07-03 05:07 UTC, shorn commented on spring-web/src/main/java/org/springframework/web/cors/DefaultCorsProcessor.java
> +			logger.debug("rejecting request because CORS processor cannot determine " +
I'm not going to get to this any time soon - feel free to reject or do own fix.

2017-07-03 07:50 UTC, sdeleuze commented
Fixed via https://github.com/spring-projects/spring-framework/commit/9901c38f9dfadafcd29113a6887e36c661962239.

2017-07-03 07:50 UTC, closed without merging