Fix bug where IllegalStateException was thrown if minPort == maxPort
spring-projects/spring-framework pull request #1612
Opened 2017-12-04 22:56 UTC by tonymitchell

Found and fixed a defect with SocketUtils.findAvailableTcpPort when minPort == maxPort

2017-12-06 23:41 UTC, sbrannen requested changes

2017-12-06 23:41 UTC, sbrannen commented on spring-core/src/test/java/org/springframework/util/SocketUtilsTests.java
> +		assertEquals(minMaxPort, port);
If port 20,000 is not available, this test is guaranteed to fail.

Thus, we should not introduce a test that is this fragile.

Please make the test robust.

2017-12-06 23:41 UTC, sbrannen commented on spring-core/src/test/java/org/springframework/util/SocketUtilsTests.java
> +	public void findAvailableTcpPortWithMinPortEqualsMaxPort() {
Please rename the method to `findAvailableTcpPortWithMinPortEqualToMaxPort()`.

2017-12-06 23:41 UTC, pivotal-issuemaster commented
@tonymitchell Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1612)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1612) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2017-12-07 00:31 UTC, sbrannen approved these changes

2017-12-07 00:38 UTC, merged