Add backslash escape support to containsSqlScriptDelimiters
spring-projects/spring-framework pull request #1919
Opened 2018-08-06 19:56 UTC by geordiecoder

Issue: SPR-17120

This change makes containsSqlScriptDelimiters keep track of backslash escapes while it determines if the current character is inside a literal.

N.B backslash escaped quotes are supported by MySQL / MariaDB but I don't believe they're supported by HSQLDB.

2018-08-06 19:57 UTC, pivotal-issuemaster commented
@geordiecoder Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1919)!

2018-08-07 14:51 UTC, sbrannen commented
Thanks for the PR!

We're looking into it.

2018-08-07 14:54 UTC, sbrannen requested changes

2018-08-07 14:54 UTC, sbrannen commented on spring-jdbc/src/main/java/org/springframework/jdbc/datasource/init/ScriptUtils.java
> +			{
Please move the opening curly bracket to the previous line as you see elsewhere in the codebase.

2018-08-07 14:54 UTC, sbrannen commented on spring-jdbc/src/main/java/org/springframework/jdbc/datasource/init/ScriptUtils.java
> +			{
Please move the opening curly bracket to the previous line as you see elsewhere in the codebase.

2018-08-07 14:54 UTC, sbrannen commented on spring-jdbc/src/main/java/org/springframework/jdbc/datasource/init/ScriptUtils.java
> +			if (thisChar == '\\')
Please rename `thisChar` to `c` for consistency with `splitSqlScript()`.

2018-08-07 19:39 UTC, geordiecoder commented
Thanks for the feedback @sbrannen - I've pushed a commit to fix the code style issues.

2018-08-13 12:01 UTC, sbrannen approved these changes

2018-08-13 12:57 UTC, sbrannen commented
This has been merged into `master` in 24ed6de6aaece130fa38e758712cedf6987212d0 and further refined in bdac39150f7137ab244590131d3d8b825ccc9e5d.

Thanks!

2018-08-13 12:57 UTC, closed without merging