Spr-17211 - async tests refactoring
spring-projects/spring-framework pull request #1941
Opened 2018-08-24 06:36 UTC by antkorwin

I fixed the problem with a fragile tests for **asynchronous events.** 

Also I add the **AsyncAssert** utility for write an asynchronous test with a better performance than test which use a **Thread.sleep(1000)**

I've a next result for pass of changed tests on my computer:
before **~30 sec.**
after  **~12 sec.**

2018-08-24 06:51 UTC, pivotal-issuemaster commented
@antkorwin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1941)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1941) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2018-08-24 06:55 UTC, pivotal-issuemaster commented
@antkorwin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=1941)!

2018-08-24 12:31 UTC, sbrannen requested changes
Thanks for the PR.

I've requested a few changes to reduce the noise in this PR. 

So let's see how it looks after you've made those changes.

2018-08-24 12:31 UTC, sbrannen commented on spring-context/src/test/java/org/springframework/context/support/SimpleThreadScopeTests.java
> +import java.util.concurrent.TimeUnit;
Please undo all changes to import ordering and use of import wildcards in this PR.

See the following for details: https://github.com/spring-projects/spring-framework/wiki/Code-Style#import-statements

2018-08-24 12:31 UTC, sbrannen commented on spring-context/src/test/java/org/springframework/scheduling/annotation/AsyncExecutionTests.java
> +		} catch (ExecutionException ex) {
Please undo all removal of newlines before `catch` statements.

See the following for details: https://github.com/spring-projects/spring-framework/wiki/Code-Style#braces

2018-08-24 12:31 UTC, sbrannen commented on spring-context/src/test/java/org/springframework/util/asyncassert/AsyncAssert.java
> +	public AsyncAssert polling(long amount, TimeUnit unit) {
Please use `java.time.Duration` instead of implementing a custom type.

2018-08-24 12:31 UTC, sbrannen commented on spring-context/src/test/java/org/springframework/util/asyncassert/AsyncAssert.java
> +	public AsyncAssert timeout(long amount, TimeUnit unit) {
Please use `java.time.Duration` instead of implementing a custom type.

2018-08-24 12:31 UTC, sbrannen commented on spring-context/src/test/java/org/springframework/util/asyncassert/AsyncAssertTest.java
> + * Created on 23.08.2018.
Please remove all such "Created on" JavaDoc entries in this PR.

2018-08-27 04:48 UTC, antkorwin commented
@sbrannen , I corrected all issues in PR, also I imported the Awaitility in dependencies and use it (with the permission of @jhoeller ).

2018-08-27 13:49 UTC, sbrannen commented
> @sbrannen , I corrected all issues in PR, also I imported the Awaitility in dependencies and use it (with the permission of @jhoeller ).

Sounds good.

I'll try to get this merged into `master` soon.

2018-08-27 13:49 UTC, sbrannen approved these changes

2018-09-04 12:53 UTC, sbrannen commented
This has been merged into `master` in ab086f4225c6e39ad322c162d997981bc27ac5f8.

Thanks

2018-09-04 12:53 UTC, closed without merging