nice to have : add empty value check
spring-projects/spring-framework pull request #23082
Opened 2019-06-04 12:24 UTC by liquanchen9

nice to have : add empty value check

2019-06-04 12:24 UTC, pivotal-issuemaster commented
@liquanchen9 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23082)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23082) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2019-06-04 13:02 UTC, pivotal-issuemaster commented
@liquanchen9 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23082)!

2019-06-04 16:09 UTC, ielatif requested changes
You can use `org.springframework.util.StringUtils#hasLength()`

2019-06-04 20:15 UTC, ielatif commented on spring-web/src/main/java/org/springframework/http/server/ServletServerHttpRequest.java
> +				if (value != null && value.length() > 0) {
You can use org.springframework.util.StringUtils#hasLength()

2019-10-02 13:52 UTC, liquanchen9 reviewed
ok

2019-10-05 06:32 UTC, rstoyanchev commented
A query parameter with an empty value is actually possible.

2019-10-05 06:32 UTC, closed without merging