Fix the bug for method mergeProperties().
spring-projects/spring-framework pull request #23290
Opened 2019-07-14 12:56 UTC by LiuMenghan

Using CollectionFactory.createStringAdaptingProperties() instead of new Properties().Using method getProperty() will get null after mergeProperties() when the value is non-string type, .

2019-07-14 12:56 UTC, pivotal-issuemaster commented
@LiuMenghan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23290)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23290) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2019-07-14 12:58 UTC, pivotal-issuemaster commented
@LiuMenghan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23290)!

2019-07-14 14:12 UTC, sbrannen requested changes
Can you please provide some background on your use case?

Also, can you please introduce tests that failed before the change and pass after the change?

2019-07-14 14:54 UTC, LiuMenghan commented
> Can you please provide some background on your use case?
> 
> Also, can you please introduce tests that failed before the change and pass after the change?

I use YamlPropertiesFactoryBean and PropertyPlaceholderConfigurer together when trying to upgrade spring and add yaml support in an old project. Some value with the type of integer in yaml file cannot be injected correctly. One alternative way to solve my problem is to use PropertySourcesPlaceholderConfigurer instead. But I still think it is a bug if someone forgetting not to use PropertyPlaceholderConfigurer like me.

2022-09-26 09:29 UTC, snicoll commented
Sorry but I don't understand the problem you're describing and, without a failing test case that shows what it is trying to solve, we can't accept the change. I am going to close this now but we can reconsider if you provide the additional context.

2022-09-26 09:29 UTC, closed without merging