Fix dataMimeType and metadataMimeType mixup
spring-projects/spring-framework pull request #23292
Opened 2019-07-15 20:27 UTC by yschimke

Mainly raising the issue I think I hit in debugging, so don't mind if someone takes this over.

2019-07-15 20:27 UTC, pivotal-issuemaster commented
@yschimke Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23292)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23292) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2019-07-15 20:28 UTC, pivotal-issuemaster commented
@yschimke Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23292)!

2019-07-16 09:09 UTC, sbrannen requested changes

2019-07-16 09:09 UTC, sbrannen commented on spring-messaging/src/main/java/org/springframework/messaging/rsocket/annotation/support/RSocketMessageHandler.java
> +		Assert.notNull(metadataMimeType, "No `metadataMimeType` in ConnectionSetupPayload and no default value");
```suggestion
		Assert.notNull(metaMimeType, "No `metadataMimeType` in ConnectionSetupPayload and no default value");
```

2019-07-16 09:10 UTC, sbrannen commented on spring-messaging/src/main/java/org/springframework/messaging/rsocket/annotation/support/RSocketMessageHandler.java
> +		Assert.notNull(metadataMimeType, "No `metadataMimeType` in ConnectionSetupPayload and no default value");
`metadataMimeType` should actually be `metaMimeType`.

I don't have "permission to push to this repository", so I'll simply perform the work locally.

2019-07-16 09:14 UTC, sbrannen commented
Resolved in 60a7092977eff8a967b6783ab3aa1f140dbe4a4f

2019-07-16 09:14 UTC, closed without merging