Add option to log HTTP method
spring-projects/spring-framework pull request #23567
Opened 2019-09-02 17:42 UTC by napstr

Ahoy,

I was surprised to neither find the http method in the log messages of the `AbstractRequestLoggingFilter` nor the option to turn them on.

This looks like a fairly uncontroversial, fully optional and backwards compatible change to me so I did not open an issue up front. I'm happy to open one if more discussion is required.

### Two things to note for the reviewer:
- [ ] I copy-pasted the method javadocs, and I'm not 100% sure if anything else needs to be done to get
```
	 * <p>Should be configured using an {@code <init-param>} for parameter name
	 * "includeHttpMethod" in the filter definition in {@code web.xml}.
```
to work. I did some CTRL-Fing for the other values and nothing interesting came up.

- [ ] I did not add a `@since 5.2` annotation as I'm not sure which version this will hit. Just amend it in :)

Cheers,
Napster

Btw, setting up the local build and running tests was a breeze, great docs!

2019-09-13 11:25 UTC, sbrannen commented
After a quick discussion with @rstoyanchev, we have decided that we should simply always include the HTTP method in those logs messages. In other words, there's no need to make it optional.

Can you please rework this PR accordingly?

2019-09-13 11:48 UTC, sbrannen commented
**Team Decision**:

After some further internal brainstorming, we have decided on the following.

- [ ] Always include the HTTP method.
- [ ] Change the format of the generated log message to the following, keeping the existing _optional_ behavior in tact for the query string, client info, headers, and payload.

Format: `<prefix><method> <uri + query string>, <client>, <session>, <user>, <headers>, <payload><suffix>`

Example: `Before request [GET /foo?x=2, client=..., session=..., user=..., headers=..., payload=...]`

@napstr, please let us know if you are willing to rework this PR along those lines.

Thanks

2019-09-13 12:03 UTC, napstr commented
Will do, I'll aim to get this done over the weekend :)

Just to clarify, did you also decide to change the existing `;`s to `, `s, @sbrannen or that a typo in the format/example?

2019-09-13 12:18 UTC, sbrannen commented
The Spring Team would also like to point out that the `logRecord()` method in the `DispatcherServlet` is capable of logging very detailed information at DEBUG and TRACE levels.

This detailed logging in the `DispatcherServlet` is available since Spring Framework 5.0 and may serve as an alternative to `AbstractRequestLoggingFilter` and its subclasses (e.g., `CommonsRequestLoggingFilter`, `ServletContextRequestLoggingFilter`, and custom implementations).

Consult the [Logging](https://docs.spring.io/spring/docs/5.1.9.RELEASE/spring-framework-reference/web.html#mvc-logging) section of the _Spring Web MVC_ documentation for further details.

2019-09-13 12:21 UTC, sbrannen commented
> Will do, I'll aim to get this done over the weekend :)

Great!

> Just to clarify, did you also decide to change the existing `;`s to `, `s, @sbrannen or that a typo in the format/example?

Yes, we decided to change the delimiter from `;` to `, ` (with the comma) in order to make it more human readable and to align with the format in `org.springframework.web.servlet.DispatcherServlet.logRequest(HttpServletRequest)`.

2019-09-14 00:37 UTC, napstr commented
How does this look?

2019-09-14 08:32 UTC, sbrannen requested changes
I think the changes look good.

I've requested simplifications to the tests. So please make those and perhaps add an additional test that's more inclusive -- for example, one that contains everything like the previously posted example: `Before request [GET /foo?x=2, client=..., session=..., user=..., headers=..., payload=...]`.

Thanks

2019-09-14 08:32 UTC, sbrannen commented on spring-web/src/test/java/org/springframework/web/filter/RequestLoggingFilterTests.java
> -	private final MyRequestLoggingFilter filter = new MyRequestLoggingFilter();
Please revert the `@BeforeEach` change. It is unnecessary and undoes the exact opposite change introduce in https://github.com/spring-projects/spring-framework/commit/08ddd1b3bc783d0dc0ef1ab5e361315cbba90e10#diff-8c84ed40b500108bc760d43f76bbdaf9R43.

2019-09-14 08:32 UTC, sbrannen commented on spring-web/src/test/java/org/springframework/web/filter/RequestLoggingFilterTests.java
> +		assertThat(filter.beforeRequestMessage).isNotNull();
```suggestion
```

2019-09-14 08:32 UTC, sbrannen commented on spring-web/src/test/java/org/springframework/web/filter/RequestLoggingFilterTests.java
> +		assertThat(filter.beforeRequestMessage.startsWith(AbstractRequestLoggingFilter.DEFAULT_BEFORE_MESSAGE_PREFIX)).isTrue();
```suggestion
		assertThat(filter.beforeRequestMessage).startsWith(AbstractRequestLoggingFilter.DEFAULT_BEFORE_MESSAGE_PREFIX);
```

With AssertJ, there's no need to check for "not null" and "is true". Simply use `.startsWith(...)` which handles both of those use cases.

Please apply the above two changes to all affected test methods.

2019-09-14 08:32 UTC, sbrannen commented on spring-web/src/test/java/org/springframework/web/filter/RequestLoggingFilterTests.java
> +		final MockHttpServletRequest request = new MockHttpServletRequest("POST", "/hotels");
```suggestion
		MockHttpServletRequest request = new MockHttpServletRequest("POST", "/hotels");
```

Please make this change to all affected test methods.

2019-09-14 08:32 UTC, sbrannen commented on spring-web/src/test/java/org/springframework/web/filter/RequestLoggingFilterTests.java
> +		assertThat(filter.beforeRequestMessage.contains("/hotel")).isTrue();
```suggestion
		assertThat(filter.beforeRequestMessage).contains("/hotel");
```

This is analogous to the aforementioned `.startsWith()` change. Please apply to all affected methods.

2019-09-14 08:32 UTC, sbrannen commented on spring-web/src/test/java/org/springframework/web/filter/RequestLoggingFilterTests.java
>  		assertThat(filter.beforeRequestMessage).isNotNull();
```suggestion
```

2019-09-14 11:22 UTC, napstr commented
@sbrannen thank you for the hints on how to improve usage of the available AssertJ api. I believe I applied all your suggestions now - let me know if anything is left.

2019-09-14 14:08 UTC, sbrannen approved these changes

2019-09-14 14:09 UTC, sbrannen commented
> @sbrannen thank you for the hints on how to improve usage of the available AssertJ api.

Glad to be of service.

> I believe I applied all your suggestions now - let me know if anything is left.

I think that looks good now. I've accepted the changes and will merge the PR in the coming days.

Enjoy your weekend!

2019-09-16 09:38 UTC, closed without merging

2019-09-16 09:39 UTC, sbrannen commented
This has been merged into `master` in 33cee066e55fea156f024bc4469fb056aba11f82, and the tests have been further polished in 52128fe86391b945a99b6611a47817a00d0b3eda.

Thanks for the PR