Improve the performance of the method MethodParameter.getParameterType
spring-projects/spring-framework pull request #23811
Opened 2019-10-15 18:08 UTC by lgxbslgx

The method ResolvableType.forMethodParameter can be unused in some cases.
See #23792.

2019-10-17 03:01 UTC, quaff commented on spring-core/src/main/java/org/springframework/core/MethodParameter.java
> +		if ("java.lang.Object".equals(paramType.getCanonicalName()) &&
It's better to use `Object.class.getName()`

2019-10-19 02:59 UTC, kowsercse requested changes

2019-10-19 02:59 UTC, kowsercse commented on spring-core/src/main/java/org/springframework/core/MethodParameter.java
> +				!"java.lang.Object".equals(getGenericParameterType().getClass().getCanonicalName())) {
Condition in the _if_ block is not readable. Extracting following code to a method with a meaningful name should be more readable.

> "java.lang.Object".equals(paramType.getCanonicalName()) &&
				!getDeclaringClass().equals(getContainingClass()) &&
				!"java.lang.Object".equals(getGenericParameterType().getClass().getCanonicalName())

2019-10-29 19:02 UTC, jhoeller commented
See my comment on the original issue: I intend to go with a simpler check along the lines of the effective behavior in 5.1.x, just checking for a containing class different from the declaring class. I've got this working locally, showing a significant enough performance difference in a microbenchmark.

As for this PR, a specific check for `java.lang.Object` doesn't seem to be ideal since an unresolved generic can expose its upper bound (which may be any type) as the plain parameter type from reflection. Also, resolving `getGenericParameterType` can be expensive on its own when just done to prevent some other expensive computation. Overall, restoring behavior along the lines of 5.1.x seems like a good enough compromise. Thanks for the PR, in any case!

2019-10-29 19:02 UTC, closed without merging