InstantFormatter ISO-formatted date parsing bug fix
spring-projects/spring-framework pull request #23895
Opened 2019-10-30 14:18 UTC by monosoul

At the moment `InstantFormatter` can serialize an `Instant` that is far in the future (or in the past), but cannot properly deserialize it, because in this case ISO-formatted instant will start with `+`/`-`-sign. This PR fixes this issue, while maintaining the previous contract.
Also, it introduces tests for `InstantFormatter` :slightly_smiling_face:

2019-10-30 14:20 UTC, pivotal-issuemaster commented
@monosoul Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=23895)!

2019-10-30 14:23 UTC, monosoul commented
@jhoeller as per our discussion at Joker conf, here's a PR to fix `InstantFormatter`

2019-10-30 16:11 UTC, sbrannen requested changes

2019-10-30 16:11 UTC, sbrannen commented on spring-context/src/test/java/org/springframework/format/datetime/standard/InstantFormatterTests.java
> +package org.springframework.format.datetime.standard;
Please add the copyright header.

2019-10-30 16:11 UTC, sbrannen commented on spring-context/src/test/java/org/springframework/format/datetime/standard/InstantFormatterTests.java
> +		final Instant expected = DateTimeFormatter.ISO_INSTANT.parse(input, Instant::from);
Please remove `final` from local variable and method parameter declarations. We (typically) do not do that in Spring Framework.

2019-10-30 17:07 UTC, sbrannen approved these changes

2019-10-30 17:26 UTC, sbrannen commented on spring-context/src/test/java/org/springframework/format/datetime/standard/InstantFormatterTests.java
> +	void should_serialize_an_instant_using_ISO_format_and_ignoring_locale(Instant input) {
How does this test ignore the locale any differently than the other test methods in this class?

2019-10-30 17:42 UTC, monosoul commented
@sbrannen thank you!

Regarding the test names (locale part), I just forgot to include this part of the contract into the test names. Should I fix it?

2019-10-30 18:35 UTC, sbrannen commented
> Regarding the test names (locale part), I just forgot to include this part of the contract into the test names. Should I fix it?

No. I think it's OK like it is.

2019-11-13 21:58 UTC, sbrannen commented
For future reference, please make sure you execute `./gradlew check` before submitting a PR.

```
[ant:checkstyle] [ERROR] /Users/XXX/spring-framework/spring-context/src/test/java/org/springframework/format/datetime/standard/InstantFormatterTests.java:1: File does not end with a newline. [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] /Users/XXX/spring-framework/spring-context/src/test/java/org/springframework/format/datetime/standard/InstantFormatterTests.java:25: Wrong order for 'java.text.ParseException' import. [ImportOrder]
```

I'll fix those locally before merging.

2019-11-14 00:38 UTC, monosoul commented
Oh, sorry for that. I can fix it myself if you didn't do that yet.

2019-11-14 08:52 UTC, sbrannen commented
> Oh, sorry for that. I can fix it myself if you didn't do that yet.

No worries. I've already handled that locally.

2019-11-14 09:02 UTC, closed without merging

2019-11-14 09:06 UTC, sbrannen commented
This has been merged into `master`.

Thanks