Supplement Test Cases In XmlBeanFactoryTests
spring-projects/spring-framework pull request #24189
Opened 2019-12-11 15:46 UTC by lixiaolong11000

Supplement Test Cases In XmlBeanFactoryTests

2019-12-11 16:02 UTC, sbrannen requested changes
I've requested a few minor changes.

2019-12-11 16:02 UTC, sbrannen commented on spring-context/src/test/resources/org/springframework/beans/factory/xml/XmlBeanFactoryTests-reftypes.xml
> +
I'm guessing `c` stands for constructor and `d` stands for depends-on, but what does `s` stand for?

In any case, I'd recommend more meaningful names -- for example, perhaps with suffixes such as `_constructor`, `_depends_on`, and `_prototype`.

2019-12-11 16:39 UTC, lixiaolong11000 commented
ok, it sounds good!  I fixed it.

2019-12-11 16:42 UTC, lixiaolong11000 commented on spring-context/src/test/java/org/springframework/beans/factory/xml/XmlBeanFactoryTests.java
> +
I removed the next line.

2019-12-11 23:50 UTC, lixiaolong11000 commented
@sbrannen  hi,I had fixed all the problems above

2019-12-13 14:10 UTC, sbrannen approved these changes

2019-12-13 15:14 UTC, closed without merging