Simplify some redundant code
spring-projects/spring-framework pull request #24586
Opened 2020-02-25 02:00 UTC by zhangt2333

I find some code to refactor using analysis : 
* Redundant `Collection.addAll()` call. It may cause one time array copy.
* The code like `this.messageBytesToRead >= input.readableByteCount() ? input.readableByteCount() : this.messageBytesToRead;` may cause one more time `input.readableByteCount()` call.

2020-02-25 09:33 UTC, sbrannen requested changes

2020-02-25 09:33 UTC, sbrannen commented on spring-expression/src/test/java/org/springframework/expression/spel/ExpressionLanguageScenarioTests.java
> +		List<Integer> primes = new ArrayList<>(Arrays.asList(2, 3, 5, 7, 11, 13, 17));
No need to create two lists in this context.

```suggestion
		List<Integer> primes = Arrays.asList(2, 3, 5, 7, 11, 13, 17);
```

2020-02-25 09:33 UTC, sbrannen commented on spring-expression/src/test/java/org/springframework/expression/spel/SpelDocumentationTests.java
> +		List<Integer> primes = new ArrayList<>(Arrays.asList(2, 3, 5, 7, 11, 13, 17));
Same as above.

```suggestion
		List<Integer> primes = Arrays.asList(2, 3, 5, 7, 11, 13, 17);
```

2020-02-25 09:46 UTC, zhangt2333 commented
@sbrannen Aha, Thanks for your code review !

2020-02-25 14:35 UTC, sbrannen commented
Thanks for making the requested changes. I plan to merge this after 5.2.4 has been released.

2020-02-26 11:29 UTC, merged

2020-02-26 11:29 UTC, sbrannen commented
This has been merged into `master`.

Thanks