Improve javadoc in RollbackRuleAttribute
spring-projects/spring-framework pull request #24682
Opened 2020-03-12 01:46 UTC by chenqimiao

In `public RollbackRuleAttribute(Class<?> clazz) `, only store the class name of the specified class, and in `private int getDepth(Class<?> exceptionClass, int depth) `, matching logic is by
`exceptionClass.getName().contains(this.exceptionName)`.
So, the enclosed class of the specified parameter of `public RollbackRuleAttribute(Class<?> clazz)` also can be match.
Suggest Improve javadoc in corresponding method.

2020-03-13 10:24 UTC, sbrannen requested changes
Please introduce a test which demonstrates that an enclosing class would result in a positive match.

2020-03-13 15:51 UTC, chenqimiao commented
@sbrannen Thank you for your review, I have submitted a unit test to demonstrate that an enclosing class would result in a positive match.

2020-03-15 11:03 UTC, sbrannen requested changes

2020-03-15 11:03 UTC, sbrannen commented on spring-tx/src/main/java/org/springframework/transaction/interceptor/RollbackRuleAttribute.java
> +	 * the supplied {@link Exception} class (, subclasses and enclosed class).
```suggestion
	 * the supplied {@link Exception} class, its subclasses, and its nested classes.
```

2020-03-15 11:04 UTC, sbrannen requested changes

2020-03-15 11:04 UTC, sbrannen commented on spring-tx/src/test/java/org/springframework/transaction/interceptor/RollbackRuleTests.java
> +	static class EnclosingException extends RuntimeException{
```suggestion
	static class EnclosingException extends RuntimeException {
```

2020-03-15 11:04 UTC, sbrannen commented on spring-tx/src/test/java/org/springframework/transaction/interceptor/RollbackRuleTests.java
> +		static class EnclosedException extends RuntimeException{
```suggestion
		static class EnclosedException extends RuntimeException {
```

2020-03-15 11:06 UTC, merged

2020-03-15 11:06 UTC, sbrannen commented
This has been merged into `master`.

Thanks