corrected javadoc
spring-projects/spring-framework pull request #24841
Opened 2020-04-01 21:07 UTC by gurpiarbassi

2020-04-01 21:07 UTC, pivotal-issuemaster commented
@gurpiarbassi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24841)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24841) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-04-01 21:08 UTC, pivotal-issuemaster commented
@gurpiarbassi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24841)!

2020-04-02 14:28 UTC, sbrannen requested changes

2020-04-02 14:28 UTC, sbrannen commented on spring-web/src/main/java/org/springframework/web/util/pattern/PathPattern.java
> + * and assign the value {@code "filename"} to the {@code filename} variable</li>
This was actually correct.

```suggestion
 * and assign the value {@code "spring"} to the {@code filename} variable</li>
```

2020-04-02 14:29 UTC, merged

2020-04-02 14:29 UTC, sbrannen commented
This has been merged into `master`.

Thanks