Simplify some control flow code
spring-projects/spring-framework pull request #24907
Opened 2020-04-14 11:20 UTC by Deycoesr

I found some control flow code can be simplify

2020-04-14 11:20 UTC, pivotal-issuemaster commented
@Deycoesr Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24907)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24907) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-04-14 11:21 UTC, pivotal-issuemaster commented
@Deycoesr Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=24907)!

2020-04-17 15:51 UTC, sbrannen requested changes
Thanks for the PR!

I requested that you revert a few of the changes for the sake of readability.

Once you make those changes, I'll be glad to merge this PR.

2020-04-17 15:51 UTC, sbrannen commented on spring-web/src/main/java/org/springframework/web/bind/support/WebRequestDataBinder.java
> +		return StringUtils.startsWithIgnoreCase(contentType, "multipart");
Good catch

2020-04-17 15:51 UTC, sbrannen commented on spring-web/src/main/java/org/springframework/web/filter/OncePerRequestFilter.java
> +		return request.getAttribute(WebUtils.ERROR_REQUEST_URI_ATTRIBUTE) != null && shouldNotFilterErrorDispatch();
Although the proposed changed is technically correct, please revert this for the sake of readability.

2020-04-17 15:51 UTC, sbrannen commented on spring-web/src/main/java/org/springframework/web/jsf/el/SpringBeanFacesELResolver.java
> +			return wac.containsBean(beanName);
Although the proposed changed is technically correct, please revert this for the sake of readability.

2020-04-17 15:51 UTC, sbrannen commented on spring-web/src/main/java/org/springframework/web/multipart/support/MultipartResolutionDelegate.java
> +			return ResolvableType.forMethodParameter(methodParam).asCollection().resolveGeneric();
Although the proposed changed is technically correct, please revert this for the sake of readability.

2020-04-17 16:17 UTC, closed without merging

2020-04-17 16:24 UTC, sbrannen commented
@Deycoesr, did you intentionally close this PR?

2020-04-17 16:27 UTC, Deycoesr commented
Not, I used `git push origin HEAD --force`.

2020-04-17 16:30 UTC, Deycoesr commented
I'm sorry, i don't know there will be such consequences. I created a new PR. #24925