Improved Tests for gh-25140
spring-projects/spring-framework pull request #25160
Opened 2020-05-28 22:56 UTC by midumitrescu

imho improved tests for gh-25140, as solicited by @jhoeller 

As promised in gh-25159, I am submitting a second suggestion for Testing the exiting code of 

```
CollectionUtils.toMultiValueMap
```

The suggestion was to create for this MultiValueMap same tests as for 

```
LinkedMultiValueMap
```

present in
```
LinkedMultiValueMapTests
```

This, however, produced a very high code duplication, which I did not find very elegant. 

I think the better way is to use Jupiter properly, to instantiate various types of MultiValueMap and test the contract for each of them. 

Like this test code is not duplicated and the contracts are consistent with each other. 

This is just a suggestion. 

I am open for suggestions  in case this does not fit your expectations.

Kind regards

2020-05-29 14:23 UTC, sbrannen requested changes
I think the use of parameterized tests is a good idea.

I've requested a few minor changes and will review again once those have been made.

2020-05-29 14:23 UTC, sbrannen commented on spring-core/src/test/java/org/springframework/util/MultiValueMapRelatedTests.java
> +						() -> asUnmodifiableMultiValueMap.setAll(exampleHashMap())),
We tend to use `Collections.singletonMap` for such use cases.

```suggestion
						() -> asUnmodifiableMultiValueMap.setAll(Collections.singletonMap("key2", "key2.value1")),
```

2020-05-29 14:23 UTC, sbrannen commented on spring-core/src/test/java/org/springframework/util/MultiValueMapRelatedTests.java
> +		objectUnderTest.put("key", values);
We tend to use `Arrays.asList` for such use cases.
```suggestion
		objectUnderTest.put("key", Arrays.asList("value1", "value2"));
```

2020-05-29 14:23 UTC, sbrannen commented on spring-core/src/test/java/org/springframework/util/MultiValueMapRelatedTests.java
> +		Assertions.assertAll(
It is not permissible to use JUnit Jupiter's `Assertions`. Doing so will actually fail the build.

Thus, please switch to AssertJ assertions and be sure to execute `./gradlew check` to verify that you don't have any Checkstyle violations in this regard.

Note: if you want something similar to `assertAll`, you may wish to use `SoftAssertions` from AssertJ.

2020-05-29 16:26 UTC, sbrannen approved these changes

2020-05-29 16:29 UTC, midumitrescu commented
@sbrannen i am on it :)

I need a couple of hours because of personal stuff and I will finish the PR afterwards.

2020-05-29 18:10 UTC, midumitrescu commented
@sbrannen done

2023-08-25 09:50 UTC, closed without merging

2023-08-25 09:50 UTC, snicoll commented
Thanks @midumitrescu, I've enabled the tests that were disabled as the fix has been added in the meantime.