refine javadoc
spring-projects/spring-framework pull request #25448
Opened 2020-07-21 15:52 UTC by XenoAmess

as title

2020-07-21 18:32 UTC, sbrannen requested changes
Thanks for the PR.

I've requested a few minor changes.

2020-07-21 18:32 UTC, sbrannen commented on spring-context/src/main/java/org/springframework/context/support/FileSystemXmlApplicationContext.java
> -	 * @see org.springframework.web.context.support.XmlWebApplicationContext#getResourceByPath
Please revert this change.

2020-07-21 18:32 UTC, sbrannen commented on spring-core/src/main/java/org/springframework/core/io/DefaultResourceLoader.java
> -	 * @see org.springframework.web.context.support.XmlWebApplicationContext#getResourceByPath
Please revert this change.

2020-07-21 18:32 UTC, sbrannen commented on spring-r2dbc/src/main/java/org/springframework/r2dbc/connection/TransactionAwareConnectionFactoryProxy.java
> + * {@link Connection}s (which implement the {@link org.springframework.jdbc.datasource.ConnectionProxy} interface) in order
Please revert this change.

This is obsolete documentation which needs to be reworked separately.

2020-07-21 18:32 UTC, sbrannen commented on spring-r2dbc/src/main/java/org/springframework/r2dbc/connection/TransactionAwareConnectionFactoryProxy.java
> +	 * The returned {@link ConnectionFactory} handle implements the {@link org.springframework.jdbc.datasource.ConnectionProxy} interface, allowing to
Please revert this change.

This is obsolete documentation which needs to be reworked separately.

2020-07-21 18:32 UTC, sbrannen commented on spring-core/src/main/java/org/springframework/core/env/ReadOnlySystemAttributesMap.java
> + * <p>Used by {@link org.springframework.core.env.AbstractEnvironment} when a {@link SecurityManager} prohibits
```suggestion
 * <p>Used by {@link AbstractEnvironment} when a {@link SecurityManager} prohibits
```

2020-07-21 18:32 UTC, sbrannen commented on spring-r2dbc/src/main/java/org/springframework/r2dbc/connection/TransactionAwareConnectionFactoryProxy.java
> +	 * @see org.springframework.jdbc.datasource.ConnectionProxy#getTargetConnection
Please revert this change.

This is obsolete documentation which needs to be reworked separately.

2020-07-22 04:46 UTC, XenoAmess commented
@sbrannen done.

2020-07-22 08:24 UTC, sbrannen approved these changes

2020-07-22 08:24 UTC, merged

2020-07-22 08:25 UTC, sbrannen commented
This has been merged into `master`.

Thanks