simplify if
spring-projects/spring-framework pull request #25449
Opened 2020-07-21 15:53 UTC by XenoAmess

as title

2020-07-21 18:41 UTC, sbrannen requested changes
Thanks for the PR.

I've requested a simple change.

2020-07-21 18:41 UTC, sbrannen commented on spring-test/src/main/java/org/springframework/test/context/web/AbstractGenericWebContextLoader.java
> +		if ((!(parent instanceof WebApplicationContext))) {
```suggestion
		if (!(parent instanceof WebApplicationContext)) {
```

2020-07-22 04:04 UTC, XenoAmess commented on spring-test/src/main/java/org/springframework/test/context/web/AbstractGenericWebContextLoader.java
> +		if ((!(parent instanceof WebApplicationContext))) {
@sbrannen done. and commits squashed.

2020-07-22 04:24 UTC, XenoAmess commented
feedback provided above.

2020-07-22 08:28 UTC, sbrannen approved these changes

2020-07-22 08:34 UTC, merged

2020-07-22 08:34 UTC, sbrannen commented
This has been merged into `master`.

Thanks