Let the DataSize.toString method returns the closest unit to represen…
spring-projects/spring-framework pull request #25556
Opened 2020-08-07 03:04 UTC by ijliym

…t the data size

So I know I configured the max upload file size is `4MB`, not `4194304B`.

2020-08-07 07:55 UTC, quaff commented
You shouldn't override default implementation, you could add a new method.

2020-08-07 09:12 UTC, snicoll requested changes
That's an interesting idea. Please update your PR to include tests that cover the various scenarios. We can figure out if we want move to a dedicated method or update the existing `toString` representation.

2020-08-09 07:54 UTC, snicoll requested changes

2020-08-09 07:54 UTC, snicoll commented on spring-core/src/test/java/org/springframework/util/unit/DataSizeTests.java
> +		assertThat(DataSize.ofKilobytes(1).toString()).isEqualTo("1KB");
Rather than only testing the happy path, I'd like to see some tests where we can't fallback to the optimisation.

2021-12-10 23:04 UTC, snicoll commented
There hasn't been much traction on this one and no feedback for over a year so I am going to close this one.

2021-12-10 23:04 UTC, closed without merging