Provide common Content-Disposition types as constants
spring-projects/spring-framework pull request #25647
Opened 2020-08-26 08:33 UTC by kashike

This adds constants for three common Content-Disposition types: `attachment`, `form-data`, and `inline`.

I have also updated the tests to use these new constants.

2020-10-02 15:04 UTC, kashike commented
Is there anything holding this pull request back? It is very simple and non-breaking.

2020-10-15 09:31 UTC, rstoyanchev commented
I think adding alternatives to the static `builder(String)` such as `formData()`, `inline()`, and `attachment()` would make the case of building more convenient than using constants and that be good enough since I'm guessing that building is the more common case.

2020-10-16 05:25 UTC, kashike commented
@rstoyanchev I have added the helper methods, but I have also kept the new constants as well, as they are still useful - for example, checking the type: `disposition.getType().equals(ContentDisposition.ATTACHMENT)`.

Let me know if this is okay with you now.

2020-10-22 08:36 UTC, rstoyanchev requested changes
Thanks I've schedule it for 5.3.

2020-10-22 08:36 UTC, rstoyanchev commented on spring-web/src/main/java/org/springframework/http/ContentDisposition.java
> +	 * @return the builder
Please add `@since 5.3` tags to all new methods.

2020-10-22 08:36 UTC, rstoyanchev commented on spring-web/src/main/java/org/springframework/http/ContentDisposition.java
> +	public static final String INLINE = "inline";
> I have also kept the new constants as well, as they are still useful - for example, checking the type: disposition.getType().equals(ContentDisposition.ATTACHMENT).

Why don't we then add `isInline`, `isAttachment`, and `isFormData` methods then?

2020-10-22 09:11 UTC, kashike commented
@rstoyanchev How does that look now?

2020-10-23 17:28 UTC, closed without merging