Correctly set auto-growing array's element
spring-projects/spring-framework pull request #26600
Opened 2021-02-24 03:38 UTC by nullzl

AbstractNestablePropertyAccessor.processKeyedProperty implementations throw IllegalArgumentException, when the property expression has more than one property key and the last key causes array to grow automatically. 
For example, a property "int[][] multiArray = new int[2][2]", property expression is "multiArray[1][3]", this method creates a new array object, and assign it to "multiArray". The new array object should be assigned to "multiArray[1]".

2021-02-24 11:13 UTC, sbrannen requested changes
Please provide a unit test that fails before the change and passes after the change -- for example, something analogous to `org.springframework.beans.BeanWrapperAutoGrowingTests.getPropertyValueAutoGrowMultiDimensionalArray()`.

Thanks

2021-02-24 16:03 UTC, nullzl commented
> Please provide a unit test that fails before the change and passes after the change -- for example, something analogous to `org.springframework.beans.BeanWrapperAutoGrowingTests.getPropertyValueAutoGrowMultiDimensionalArray()`.
> 
> Thanks

Thank you very much for your review. I have added  a unit test org.springframework.beans.BeanWrapperAutoGrowingTests.setPropertyValueAutoGrowMultiDimensionalArray().

2021-02-24 17:27 UTC, sbrannen approved these changes

2021-02-25 10:43 UTC, closed without merging

2021-02-25 10:58 UTC, sbrannen commented
This has been merged into `master` in a33eac3ec05952424603d1fefc627b4a3ef36449, revised in 8baf404893037951ac29393a41d40af4fa11775b, and backported to `5.2.x`.

Thanks for catching _and_ fixing this bug!