Message and stream level data  and accept  mime
spring-projects/spring-framework pull request #26621
Opened 2021-02-28 14:29 UTC by rudy2steiner

Implemention of issue #26379

2021-03-03 03:07 UTC, rudy2steiner commented
@rstoyanchev PTAL

2021-03-09 15:55 UTC, rstoyanchev requested changes
Some high level feedback. 

To start, the `MetadataMimeCodec` should be in RSocket-Java, not here. I've created https://github.com/rsocket/rsocket-java/issues/996 for that.

On the side of RSocketRequester, I can see potentially methods to set the mimeTypes or acceptMimeTypes for a request but no need more generally to introduce the concept of "headers".

Some classes, like `AbstractEncoderMethodReturnValueHandler.java`, are intended to be more generally used and this is why they are not in the `rsocket` package. Such classes cannot have RSocket dependencies.

2021-03-15 12:24 UTC, rudy2steiner commented
> Some classes, like `AbstractEncoderMethodReturnValueHandler.java`, are intended to be more generally used and this is why they are not in the `rsocket` package. Such classes cannot have RSocket dependencies.

I agree with MetadataMimeCodec should be in Rsocket-java, and do you have more specific feedbacks how to implement contentType and acceptMimes .

2021-04-05 11:19 UTC, rudy2steiner commented
@rstoyanchev thanks for your feedbacks, updated!

2023-08-29 15:46 UTC, rstoyanchev requested changes
@rudy2steiner, I've reviewed the PR and added a few comments.

2023-08-29 15:46 UTC, rstoyanchev commented on spring-messaging/src/main/java/org/springframework/messaging/rsocket/annotation/support/MessagingRSocket.java
> +	}
Likewise here, when accessed `CONTENT_TYPE` should be expected to be a single `MimeType`.

2023-08-29 15:46 UTC, rstoyanchev commented on spring-messaging/src/main/java/org/springframework/messaging/rsocket/annotation/support/RSocketPayloadReturnValueHandler.java
> +		responseRef.set(encodedContent.switchOnFirst((signal, inner) -> {
We shouldn't automatically use `switchOnFirst`. If no content negotiation took place, and the application is using the connection-wide `dataMimeType`, there is no need to use this operator.

2023-08-29 15:46 UTC, rstoyanchev commented on spring-messaging/src/main/java/org/springframework/messaging/rsocket/DefaultRSocketRequester.java
> +		}
Likewise on the requester side, we should be aware if a request specific content type is being used, and if not then avoid using the `switchOnFirst` operator.

2023-08-29 15:46 UTC, rstoyanchev commented on spring-messaging/src/main/java/org/springframework/messaging/handler/invocation/reactive/HandlerMethodReturnValueHandler.java
> +	String RESPONSE_CONTENT_TYPE = "responseContentType";
It's not clear what the purpose of this header is. It seems to be set as an empty AtomicReference from `MessagingRSocket` in the beginning, and then its value is set from `AbstractEncoderMethodReturnValueHandler`, but I don't see anything making use of it.

2023-09-08 13:42 UTC, rstoyanchev commented
Closing for now as the PR needs significant updates, but we have #26379 to keep track of the request.

2023-09-08 13:42 UTC, closed without merging