Fix test context bootstrapper inheritance override
spring-projects/spring-framework pull request #26645
Opened 2021-03-06 15:11 UTC by antoinemeyer

`BootstrapWith` as a meta override should be considered on the test class and all ancestors, not just the direct test class.

----

It is common to use a base test class such as:
```
@SpringBootTest
public abstract class BaseTest {
}
```
Annotating this `BaseTest` with `@BootstrapWith(XXX)` should not cause a `java.lang.IllegalStateException: Configuration error: found multiple declarations of @BootstrapWith` but instead properly use the `@BootstrapWith` as an override of the bootstrap provided as meta by @SpringBootTest.

2021-03-06 15:11 UTC, pivotal-issuemaster commented
@antoinemeyer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26645)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26645) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-03-06 15:12 UTC, pivotal-issuemaster commented
@antoinemeyer Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26645)!

2023-09-06 08:29 UTC, sbrannen requested changes
If you have time to update this PR regarding the aforementioned pitfall, please let me know.

Otherwise, I will take a closer look in the `6.1.x` time frame.

2023-10-24 10:04 UTC, closed without merging

2023-10-24 10:04 UTC, sbrannen commented
- superseded by #31485