fix : fix invalid annotation
spring-projects/spring-framework pull request #26805
Opened 2021-04-14 14:22 UTC by e406hsy

https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-factorybeans-annotations
At first example of 1.10.5. Defining Bean Metadata within Components
`@Component` should be `@Configuration.

2021-04-14 14:22 UTC, pivotal-issuemaster commented
@e406hsy Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26805)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26805) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-04-14 14:23 UTC, pivotal-issuemaster commented
@e406hsy Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26805)!

2021-04-14 16:58 UTC, hrybs requested changes

2021-04-14 16:58 UTC, hrybs commented on src/docs/asciidoc/core/core-beans.adoc
> +	@Configuration
The documentation is correct.
We can define methods with **@Bean** annotation inside any **@Component** classes.

2021-04-14 16:58 UTC, hrybs commented on src/docs/asciidoc/core/core-beans.adoc
> +	@Configuration
The documentation is correct.
We can define methods with **@Bean** annotation inside any **@Component** classes.

2021-04-15 07:24 UTC, snicoll commented
@e406hsy the section of the documentation you've changed is "Defining Bean Metadata within Components". As @hrybs indicated, although unusual, it is possible to create additional beans in a component (so-called "lite mode") and those changes are not required. Thanks again for the PR, in any case.

2021-04-15 07:24 UTC, closed without merging