Add two test cases to MessageBodyClientHttpResponseWrapper class
spring-projects/spring-framework pull request #26984
Opened 2021-05-27 08:42 UTC by Yin-Jui

Adding two test cases to test the correctness of hasEmptyMessageBody in MessageBodyClientHttpResponseWrapper class, which improves the method coverage.

2021-05-27 08:42 UTC, pivotal-cla commented
@Yin-Jui Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26984)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26984) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-05-27 12:29 UTC, sbrannen requested changes
Hi @Yin-Jui,

Thanks for submitting your first PR!

I've requested a few minor changes.

2021-05-27 12:29 UTC, sbrannen commented on spring-web/src/test/java/org/springframework/web/client/MessageBodyClientHttpResponseWrapperTests.java
> +package org.springframework.web.client;
Please add the missing copyright header with the date range set to 2002-2021.

See `HttpMessageConverterExtractorTests` for an example.

2021-05-27 12:29 UTC, sbrannen commented on spring-web/src/test/java/org/springframework/web/client/MessageBodyClientHttpResponseWrapperTests.java
> +public class MessageBodyClientHttpResponseWrapperTests {
```suggestion
class MessageBodyClientHttpResponseWrapperTests {
```

2021-05-27 12:29 UTC, sbrannen commented on spring-web/src/test/java/org/springframework/web/client/MessageBodyClientHttpResponseWrapperTests.java
> +	public void testMessageBodyNotExist() throws IOException {
```suggestion
	void messageBodyDoesNotExist() throws IOException {
```

2021-05-27 12:29 UTC, sbrannen commented on spring-web/src/test/java/org/springframework/web/client/MessageBodyClientHttpResponseWrapperTests.java
> +	public void testMessageBodyExist() throws IOException {
```suggestion
	void messageBodyExists() throws IOException {
```

2021-05-27 12:29 UTC, sbrannen commented on spring-web/src/test/java/org/springframework/web/client/MessageBodyClientHttpResponseWrapperTests.java
> +		ClientHttpResponse response = new ClientHttpResponse() {
Please remove the anonymous inner class and replace it with a Mockito mock.

See `HttpMessageConverterExtractorTests` for an example.

Please do this for both test methods.

2021-05-27 12:29 UTC, sbrannen commented on spring-context-support/src/main/java/org/springframework/mail/MailAuthenticationException.java
> +
Please revert this formatting change since it is not related to this PR.

2021-06-09 23:36 UTC, pivotal-cla commented
@Yin-Jui Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=26984)!

2021-06-10 03:38 UTC, Yin-Jui commented
Hello @sbrannen, Thank you for the advice! I already fixed the pull request as recommended

2021-09-07 12:26 UTC, closed without merging

2021-09-07 12:27 UTC, sbrannen commented
This has been merged into `main` in 417bce8be5e32ae43c2e3b25de1e24cd03c71e93 and revised in d8191b48088b0ac2843b64beac861ddfcb99d9dd.

Thanks