Fix ReactorClientHttpRequest::getHeaders implementation to provide actually committed headers to the public API
spring-projects/spring-framework pull request #27768
Opened 2021-12-06 09:40 UTC by sokomishalov

Fixes issues like [that](https://github.com/zalando/logbook/pull/1150#issuecomment-986223607), when public API does not expose headers that have been set by connector implementation.

2021-12-06 11:34 UTC, rstoyanchev requested changes
The change might not be implemented in exactly this way. For example we don't use protected fields. 

Rather than providing a solution, please updated the description of the pull request in order to describe the problem, and not just reference some external issue which requires additional context.

2021-12-07 15:26 UTC, sokomishalov commented
@rstoyanchev Fair enough
The problem is that `ClientHttpRequest::getHeaders` contain only headers that have been applied via `WebClient` API and don't contain headers applied by an underlying connector, (i.e. "user-agent").
Regarding implementation with restriction on protected fields - should this logic be duplicated to the `ReactorClientHttpRequest`?

2022-01-07 13:56 UTC, rstoyanchev requested changes
Thanks for elaborating. 

We have a `NettyHeadersAdapter` that's used to expose the underlying headers on the response. We can enable the same on the request side. So, rather than exposing all the protected fields, I would suggest a protected `initReadOnlyHeaders` method that can be overridden in sub-classes. For Reactor Netty, it would be:
```java
@Override
protected HttpHeaders initReadOnlyHeaders() {
	return HttpHeaders.readOnlyHttpHeaders(new NettyHeadersAdapter(request.requestHeaders()));
}
```
Let me know if you plan to update the PR, or otherwise I'll take it from here.

2022-01-10 08:57 UTC, sokomishalov commented
@rstoyanchev totally makes sense, I've reworked it according to your recommendations (netty, apache http 5, jetty).
p.s. I've noticed you marked these changes to the 6.x milestone - is there any chance this enhancement to be backported on 5.x ?

2022-01-11 18:49 UTC, closed without merging