support spel in AsyncExecutionAspectSupport
spring-projects/spring-framework pull request #28549
Opened 2022-05-31 23:54 UTC by dawn9117

2022-06-01 01:51 UTC, dawn9117 commented
> spel is already supported.

Okay, but such as @Async (" ${executor.name:} ") doesn't work  when executor.name not configured.
Additionally EmbeddedValueResolver can be reused.

2022-06-01 14:47 UTC, sbrannen commented
### Related Issues

-  #27818

2022-06-01 14:54 UTC, sbrannen requested changes
Please make the requested change and introduce a test that fails before this PR and passes after this PR.

2022-06-01 14:54 UTC, sbrannen commented on spring-aop/src/main/java/org/springframework/aop/interceptor/AsyncExecutionAspectSupport.java
> +				qualifier = stringValueResolver.resolveStringValue(qualifier);
This change currently [fails the build](https://ci.spring.io/builds/190047#L62728b6d:254:256).

```suggestion
			if (this.stringValueResolver != null && StringUtils.hasLength(qualifier)) {
				qualifier = this.stringValueResolver.resolveStringValue(qualifier);
```

2022-06-04 02:11 UTC, dawn9117 commented
> Please make the requested change and introduce a test that fails before this PR and passes after this PR.

I've already added it. Please review, thanks.

2022-10-05 14:43 UTC, sbrannen commented
> I've already added it. Please review, thanks.

Thanks for making the requested changes. I'll see about getting it merged in.

2022-10-05 14:43 UTC, sbrannen approved these changes

2022-10-07 14:39 UTC, closed without merging

2022-10-07 14:40 UTC, sbrannen commented
This has been merged into `main`.

Thanks 👍