Instanceof pattern matching + small code refactoring
spring-projects/spring-framework pull request #29222
Opened 2022-09-29 15:35 UTC by Drezir

2022-10-10 11:23 UTC, r331 commented on spring-context/src/main/java/org/springframework/context/annotation/BeanMethod.java
> +				this.metadata.equals((beanMethod).metadata)));
Maybe without braces? this.metadata.equals(beanMethod.metadata)));

2022-11-21 16:23 UTC, sbrannen requested changes
Thanks for the PR.

I've requested some changes.

If you shift the focus of this PR to "instanceof pattern matching", the work can be merged sooner.

2022-11-21 16:23 UTC, sbrannen commented on spring-context/src/main/java/org/springframework/cache/interceptor/SimpleCacheResolver.java
>  	}
This is the standard code style in Spring Framework.

Please revert.

2022-11-21 16:23 UTC, sbrannen commented on spring-context/src/main/java/org/springframework/context/annotation/BeanMethod.java
> +				this.metadata.equals((beanMethod).metadata)));
```suggestion
				this.metadata.equals(beanMethod.metadata)));
```

2023-01-29 13:21 UTC, closed without merging

2023-01-29 13:23 UTC, sbrannen commented
Thanks for the PR.

Due to lack of feedback on the requested changes, I have merged parts of this PR into `main` in 8783075e40881c8ca2ee52d81c76e2f6149ace38 with further refinements in e0f60dc09d9515809963f066cdfdacebd66b0042.