Small polish
spring-projects/spring-framework pull request #29460
Opened 2022-11-10 13:53 UTC by divcon

1.  Remove unused return value
2. Add Nullable annotaions

2022-11-21 16:11 UTC, sbrannen requested changes

2022-11-22 06:03 UTC, divcon commented on spring-web/src/main/java/org/springframework/web/context/request/ServletWebRequest.java
> +		if (lastModifiedTimestamp < 0 || ifUnmodifiedSince == -1) {
I reverted it.

2022-11-22 06:03 UTC, divcon commented on spring-web/src/main/java/org/springframework/web/context/request/ServletWebRequest.java
> +	private void validateIfModifiedSince(long lastModifiedTimestamp) {
I reworked it.

2022-11-22 06:04 UTC, divcon commented on spring-web/src/main/java/org/springframework/web/server/adapter/DefaultServerWebExchange.java
> +					|| CollectionUtils.isEmpty(getRequest().getHeaders().get(HttpHeaders.IF_MATCH))) {
I reverted it.

2022-11-22 06:06 UTC, divcon commented
@sbrannen 
Thank you for your kind review.
I reflected your review.

2022-11-22 13:04 UTC, sbrannen approved these changes

2022-11-22 13:36 UTC, closed without merging

2022-11-22 13:37 UTC, sbrannen commented
This has been merged into `main` in c12d93c5d1696fc030b7b2fc0fb999b99795c59c and revised in a832c98cedc56690ad606b53f497814370792d12.

Thanks