Restrict forwards in MockMvcWebConnection to 100
spring-projects/spring-framework pull request #29557
Opened 2022-11-23 06:38 UTC by manthanb

When a filter is configured to conditionally forward, and it is configured to handle FORWARD dispatches as well, and it prevents infinite forward loops by either extending OncePerRequestFilter or otherwise using request attributes, this can result in infinite forward loops in WebClient tests using MockMvcWebConnection. This change will restrict the maximum number of forwards in MockMvcWebConnection to 100.

Closes gh-29483

2023-01-06 03:31 UTC, manthanb commented
Hey @sbrannen,
I am not sure if you are the right person to reach out to, and I am very sorry if you are not.
I was wondering whenever you have some time, if you can take a quick look at this request and see if it fixes the issue of potential infinite loop with MockMvcWebConnection - https://github.com/spring-projects/spring-framework/issues/29483.

2023-01-20 18:40 UTC, simonbasle requested changes
@manthanb thanks for the contribution. I think that throwing an exception as proposed in the original issue would be better, wdyt? The message can mention that there is a probable infinite loop and that it forwarded 100 times.

2023-01-27 13:34 UTC, simonbasle commented
@manthanb are you still able to work on this? (cf review above)

2023-01-27 17:11 UTC, manthanb commented
Hi @simonbasle Very sorry I missed your last comment. Yes, I will make the changes and commit today.

2023-02-01 08:57 UTC, simonbasle commented
(note: to be backported in 5.3.x, as tracked by gh-29866)

2023-02-07 15:19 UTC, simonbasle approved these changes
I went ahead and made the adjustments to throw rather than ignore

2023-02-07 15:23 UTC, merged