Clarify behavior of the Elvis SpEL operator in documentation
spring-projects/spring-framework pull request #30352
Opened 2023-04-18 15:35 UTC by simonbasle

This commit improves both the javadoc and the reference guide section on
the Elvis SpEL operator to clarify that in addition to `null` objects,
empty Strings also lead the operator to evaluate to its second operand.

The reference guide's advanced snippet is modified to use such an empty
String instead of `null` to make that behavior prominent with some code.

See gh-30318

2023-04-18 15:36 UTC, simonbasle commented
`draft` while waiting for reference guide changes that we might need to adapt to / rebase on.

2023-04-19 15:42 UTC, sbrannen requested changes
I made some suggestions to improve the wording and grammar.

2023-04-19 15:42 UTC, sbrannen commented on framework-docs/src/docs/asciidoc/core/core-expressions.adoc
> +NOTE: The SpEL Elvis operator actually also checks for empty Strings, in addition to null objects.
```suggestion
NOTE: The SpEL Elvis operator also checks for _empty_ Strings in addition to `null` objects.
```

2023-04-19 15:42 UTC, sbrannen commented on spring-expression/src/main/java/org/springframework/expression/spel/ast/Elvis.java
> + * nor the empty String, the value of the expression is <code>a</code>.
```suggestion
 * Represents the Elvis operator <code>?:</code>. For an expression <code>a?:b</code> if <code>a</code> is neither null
 * nor an empty String, the value of the expression is <code>a</code>.
```

2023-04-19 15:42 UTC, sbrannen commented on spring-expression/src/main/java/org/springframework/expression/spel/ast/Elvis.java
> +	 * If it is null or the empty String, return the other value.
```suggestion
	 * Evaluate the condition and if neither null nor an empty String, return it.
	 * If it is null or an empty String, return the other value.
```

2023-05-05 14:10 UTC, simonbasle commented
Rebased on top of Antora changes, ready for merge.

2023-05-05 14:13 UTC, merged