Add MultipartFileArgumentResolver.
spring-projects/spring-framework pull request #30728
Opened 2023-06-22 16:38 UTC by OlgaMaciaszek

- [ ] add tests
- [ ] add more javadocs

2023-06-23 15:01 UTC, OlgaMaciaszek commented
Fixes gh-30342.

2023-06-23 15:18 UTC, rstoyanchev requested changes
Overall looks good. Some minor comments below.

2023-06-23 15:18 UTC, rstoyanchev commented on spring-web/src/main/java/org/springframework/web/service/invoker/MultipartFileArgumentResolver.java
> +				null, MULTIPART_FILE_LABEL, true);
You can pass the name as `""`. It's checked later on in the base class and updated.

2023-06-23 15:18 UTC, rstoyanchev commented on spring-web/src/main/java/org/springframework/web/service/invoker/MultipartFileArgumentResolver.java
> +			headers.setContentType(MediaType.parseMediaType(file.getContentType()));
We can avoid parsing here, and use `headers.addHeader(HttpHeaders.CONTENT_TYPE, file.getContentType())`.

2023-06-23 15:18 UTC, rstoyanchev commented on spring-web/src/main/java/org/springframework/web/service/invoker/MultipartFileArgumentResolver.java
> +				"The value has to be of type 'MultipartFile'");
`Assert.state` would be more appropriate here, `IllegalStateException` vs `IllegalArgumentException`.

2023-06-27 09:00 UTC, rstoyanchev approved these changes
Thanks for the updates, and for adding an integration test.

2023-06-27 09:52 UTC, closed without merging