Extract refresh() method from AbstractRoutingDataSource
spring-projects/spring-framework pull request #31248
Opened 2023-09-16 14:40 UTC by violetbeach

Situation is that you want to add DataSource to the DataSources of AbstractRoutingDataSource during runtime.

When i put a Data Source, I need to synchronize target Data Sources to resolved Data Sources.

At that time, I call `afterPropertiesSet()` as below.

```java
public DataSource createNewDataSource() throws SQLException {
    customDataSource = new CustomDataSource(); // CustomDataSource implements AbstractRoutingDataSource
    customDataSource.setTargetDataSources(dataSourceMap);
    customDataSource.setDefaultTargetDataSource(defaultDataSource());
    multiDataSource.afterPropertiesSet(); // unclear intentions
    return multiDataSource;
}
```

However, `afterPropertiesSet()` is unclear.

So I suggest extract `refresh()` method. Then, intent can be exposed.

Please feel free to share your opinions or advice.

thanks you.

2023-09-19 08:23 UTC, sbrannen requested changes
Thanks for the proposal and PR.

Can you please also introduce a similar `refresh()` method in `AbstractRoutingConnectionFactory` along with a corresponding test?

2023-09-19 12:41 UTC, violetbeach commented
> Can you please also introduce a similar `refresh()` method in `AbstractRoutingConnectionFactory` along with a corresponding test?

Sure. I've done.

Please let me know if you need anything else. Thank you for your review!

2023-09-25 12:51 UTC, sbrannen requested changes
Thanks for making the changes to `AbstractRoutingConnectionFactory` as well.

After further consideration, the team has decided that we would like these new methods to be named `initialize()` instead of `refresh()`, since the latter implies that there is first class support for dynamic refreshes at runtime -- which is not the case.

2023-09-25 12:51 UTC, sbrannen commented on spring-jdbc/src/main/java/org/springframework/jdbc/datasource/lookup/AbstractRoutingDataSource.java
> +	public void refresh() {
Please rename to `initialize()`.

2023-09-25 12:51 UTC, sbrannen commented on spring-r2dbc/src/main/java/org/springframework/r2dbc/connection/lookup/AbstractRoutingConnectionFactory.java
> +	public void refresh() {
Please rename to `initialize()`.

2023-09-25 14:32 UTC, violetbeach commented
> After further consideration, the team has decided that we would like these new methods to be named `initialize()` instead of `refresh()`, since the latter implies that there is first class support for dynamic refreshes at runtime -- which is not the case.

I get it.

Thank you for considering it and the kind comment!

2023-09-26 11:14 UTC, sbrannen approved these changes

2023-09-26 13:13 UTC, closed without merging

2023-09-26 13:14 UTC, sbrannen commented
This has been merged into `main` in 6d2d8a36c2b608e0c127efa20ef9ea8f8238ff84 and revised in d50ec68ad7bbbc195353e1ba59e2a613bc80013a.

Thanks for the contribution, and congratulations on getting your first PR for the Spring Framework merged! 👍