Exclude Part and MultipartFile from nested constructor binding on WebFlux
spring-projects/spring-framework pull request #31778
Opened 2023-12-07 07:04 UTC by HeartPattern

Related to: https://github.com/spring-projects/spring-framework/issues/31669 and https://github.com/spring-projects/spring-framework/commit/9ade52dbe25bdcf5751590c98bacfe7053f5dddf

WebFlux has same issue with nullable multipart file handling. MultipartFile and Part should be excluded from nested constructor binding in WebExchangeDataBinder.

2023-12-07 07:04 UTC, pivotal-cla commented
@HeartPattern Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=31778)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=31778) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-12-07 07:05 UTC, pivotal-cla commented
@HeartPattern Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=31778)!

2023-12-08 13:08 UTC, sbrannen requested changes
Can you please introduce a test that fails before the change and passes after the change?

2023-12-09 14:01 UTC, sbrannen commented
> However, it seems like Part and FilePart is not the only problem. Any other nullable types is not bind properly through constructor after [ea398d7](https://github.com/spring-projects/spring-framework/commit/ea398d7b7e72d1e1a9f7a002a291f4e0b8660e70). For example, in kotlin

@HeartPattern, can you please create a separate issue to discuss that?

2023-12-09 14:18 UTC, HeartPattern commented
Open another PR addressing that problem.
https://github.com/spring-projects/spring-framework/pull/31800

2023-12-11 13:16 UTC, sbrannen approved these changes

2023-12-12 13:25 UTC, rstoyanchev commented on spring-web/src/main/java/org/springframework/web/bind/support/WebExchangeDataBinder.java
> +	}
This is a necessary change indeed for `Part` but `MultipartFile` is not used in WebFlux, so we can leave that out.

2023-12-12 15:42 UTC, rstoyanchev commented
I'm processing this locally as we are close to the 6.1.2 release. No need send further updates.

2023-12-12 16:02 UTC, closed without merging