Add default UTF-8 charset to ContentRequestMatchers for multipartData handling
spring-projects/spring-framework pull request #31924
Opened 2023-12-29 18:29 UTC by azdanov

This should resolve https://github.com/spring-projects/spring-framework/issues/31923

I've added default UTF-8 charset to be used in `DiskFileItemFactory`.

This should allow ContentRequestMatchers to correctly handle multipartData which contains unicode.

2023-12-29 18:29 UTC, pivotal-cla commented
@azdanov Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=31924)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=31924) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-12-29 18:30 UTC, pivotal-cla commented
@azdanov Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=31924)!

2024-01-15 11:42 UTC, rstoyanchev requested changes
Let me know if you agree with the proposed change below and whether you'd like to do it?

2024-01-15 11:42 UTC, rstoyanchev commented on spring-test/src/main/java/org/springframework/test/web/client/match/ContentRequestMatchers.java
> +				fileUpload.setFileItemFactory(factory);
Switching the general default could break existing tests, and that should wait for a major or minor release. In the meantime, we could narrow the scope and default to UTF-8 specifically for JSON. That would be safer and addresses the original issue.

2024-01-15 12:14 UTC, azdanov commented
I agree, but I don't have time now. So feel free to add.

2024-03-12 10:43 UTC, closed without merging