Remove unnecessary semicolons
spring-projects/spring-framework pull request #32069
Opened 2024-01-20 11:37 UTC by mnhock

2024-01-20 13:29 UTC, snicoll requested changes
Thanks for the PR but please review the commit to make sure you don't introduce unrelated change. From the GitHub UI I gather the formatting has changed.

2024-01-20 13:29 UTC, snicoll commented on spring-context/src/main/java/org/springframework/context/annotation/EnableLoadTimeWeaving.java
> +  }
This formatting change should be reverted (same on the three other occurrences.

2024-01-20 14:05 UTC, sbrannen commented
Thanks for the PR.

Unfortunately we don't have a policy stating that we remove semicolons in enum declarations.

In light of that, I am closing this PR.

2024-01-20 14:05 UTC, closed without merging

2024-01-21 15:35 UTC, sbrannen commented
Hi @mnhock,

Traditionally we had a mix of enum constant declarations with and without the closing semicolon; however, apparently all of the unnecessary semicolons have been removed over the years except the last four that you updated in this PR.

In light of that, I decided to merge your PR (see a8fa98e2a6ddc28febb07303eab644efe3162025 and 5856d2e54efe9209e415b0547174cd754473d6cc) in order to achieve consistency across the code base, and we'll consider making it an official policy in our Code Style.

Cheers,

Sam

2024-01-21 16:47 UTC, mnhock commented
Hi @sbrannen!

Thanks for merging the PR and providing clarity on the consistency across the code base. I appreciate your attention to this and the effort to maintain a unified coding style. 


Thanks to the awesome Spring Team!