Fix return value validation
spring-projects/spring-framework pull request #33105
Opened 2024-06-27 03:07 UTC by imvtsl

Fix argument in call to applyReturnValueValidation() method in MethodValidationInterceptor.java. Method argument was passed instead of the return value of the method that was being validated.

Closes gh-33092

2024-06-27 03:07 UTC, pivotal-cla commented
@imvtsl Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=33105)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=33105) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-06-27 03:08 UTC, pivotal-cla commented
@imvtsl Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=33105)!

2024-06-27 03:10 UTC, imvtsl commented
@rstoyanchev
Please review.

2024-06-27 08:10 UTC, rstoyanchev requested changes
It would be good to have a test. Would you like to add one, possibly in `MethodValidationProxyReactorTests` or `MethodValidationProxyTests`?

2024-06-27 22:35 UTC, imvtsl commented
Sure. I am working on adding test now.

2024-06-28 00:51 UTC, imvtsl commented
@rstoyanchev 
I added tests to MethodValidationProxyTests.
In tests, I changed expected exception from ValidationException to ConstraintViolationException as ConstraintViolationException is more specific. I hope that's okay?

I read [CONTRIBUTING.md](https://github.com/spring-projects/spring-framework/blob/main/CONTRIBUTING.md#submit-a-pull-request) and I have a query. Should I sqaush these 2 commits into one or is it okay?

2024-06-28 14:36 UTC, closed without merging

2024-06-28 14:38 UTC, rstoyanchev commented
I've squashed them for you and updated the tests a bit.