Fix value accumulation for case-sensitive keys in NettyHeadersAdapter
spring-projects/spring-framework pull request #33730
Opened 2024-10-17 07:33 UTC by qnnn

The current `NettyHeaders` supports case-sensitive storage of entry values when using the `add` method. This causes the `NettyHeadersAdapter` to accumulate the values for the corresponding key when retrieving headers(see unit test). 

Add a unit test testHeadersOutput to verify the final output of the headers.

2024-10-17 12:04 UTC, qnnn commented
Oh, addAll has the same issue. I will add another commit.

2024-10-23 02:15 UTC, qnnn commented
@simonbasle Thanks for your patience in explaining this. Yes, I can confirm that the duplication of values for a given header name happens on the wire (confirmed via Wireshark). 

It seems that some Spring Cloud Gateway's `header filters` are causing this issue when they transform the `NettyHeaderAdapter` into `MultiValueMapAdapter<>(new LinkedCaseInsensitiveMap<>(8, Locale.ENGLISH))` (such as in `org.springframework.cloud.gateway.filter.headers.RemoveHopByHopHeadersFilter#filter`).
![image-20241023100244781](https://github.com/user-attachments/assets/20afdc7c-a2c2-4541-b72b-20866c1c89f8)

I feel that `MultiValueMapAdapter<>(new LinkedCaseInsensitiveMap<>(8, Locale.ENGLISH))` is a standards-compliant header implementation, and when other header adapters are converted to it, they should produce the same result (case-insensitive).

2024-10-28 08:54 UTC, sdeleuze commented
@qnnn Is this use case of headers filtering/reconstruction in `org.springframework.cloud.gateway.filter.headers.RemoveHopByHopHeadersFilter` is the only concrete bug you face or are there other ones (if yes, which ones)?

2024-10-28 10:39 UTC, qnnn commented
@sdeleuze Yes, I have verified that there are others as well: 

- org.springframework.cloud.gateway.filter.headers.XForwardedHeadersFilter
- org.springframework.cloud.gateway.filter.headers.ForwardedHeadersFilter

Any implementation that iterates through the `MultiValueMap`'s `entrySet` and then uses `addAll` may have this issue. Such as(I haven’t verified this yet; it's just a guess):

+ org.springframework.cloud.gateway.filter.WebsocketRoutingFilter
+ org.springframework.cloud.gateway.filter.headers.TransferEncodingNormalizationHeadersFilter
+ org.springframework.cloud.gateway.filter.factory.cache.CachedResponse$Builder#headers

2024-10-28 11:10 UTC, sdeleuze commented
Thanks, that helps. We are discussing the best strategy to fix those bugs while keeping a great performance/efficiency. We will get back to you once we have made a decision.

2024-10-28 12:37 UTC, qnnn commented
> Thanks, that helps. We are discussing the best strategy to fix those bugs while keeping a great performance/efficiency. We will get back to you once we have made a decision.

@sdeleuze It's ok, I understand. 

Perhaps maintaining a `caseInsensitiveKeyMap` to store case-insensitive keys might help with performance—(please disregard if it’s not useful.)

When operating on `NettyHeaders`, the following map could be updated simultaneously:

```java
    Map<String, String> map = new LinkedCaseInsensitiveMap<>(8, Locale.ENGLISH);
    String headerKey = map.compute("TestHeader", (caseInsensitiveKey, headerKey) -> {
        if (!StringUtils.hasText(headerKey)){
	    return caseInsensitiveKey;
	}
	return headerKey;
    });
```
Something similar:
![未命名文件](https://github.com/user-attachments/assets/76ddd60a-693b-4ec7-8bd5-79193a56a6aa)

2024-10-28 14:25 UTC, simonbasle requested changes
Correct me if I'm wrong, but the headers case variants are populated by Netty itself, i.e. it comes from the wire. In that case you are addressing the wrong issue. 

The change and tests that you proposed impact the intermediate `Netty4HeadersAdapter` (adapting Netty `DefaultHttpHeaders` to `MultiValueMap<String, String>`)... but if you add the test's headers to `DefaultHttpHeader` instance itself, then construct a `Netty4HeadersAdapter` out of it, tests fail again despite your changes:

```java

	@Test
	void prepopulatedNativeNetty4() {
		DefaultHttpHeaders native = new DefaultHttpHeaders();
		native.add("TestHeader", "first");
		native.add("TestHEADER", "second");
		native.add("SecondHeader", "value");
		native.add("TestHeader", "third");

		MultiValueMap<String, String> adapter = new Netty4HeadersAdapter(native);

		//copying native headers into a new HttpHeaders
		HttpHeaders headers = new HttpHeaders();
		for (Map.Entry<String, List<String>> entry : adapter.entrySet()) {
			headers.addAll(entry.getKey(), entry.getValue());
		}

		assertThat(headers.get("TestHeader")).as("TestHeader")
				.containsExactly("first", "second", "third");
	}
```

2024-10-28 14:27 UTC, simonbasle commented
@qnnn we continue evaluating the possible fixes and their impact. I will probably close this PR in favor of creating a new issue tracking this, in which case I'll ping you in there.

2024-10-28 15:02 UTC, qnnn commented
> Correct me if I'm wrong, but the headers case variants are populated by Netty itself, i.e. it comes from the wire. In that case you are addressing the wrong issue.
> 
> The change and tests that you proposed impact the intermediate `Netty4HeadersAdapter` (adapting Netty `DefaultHttpHeaders` to `MultiValueMap<String, String>`)... but if you add the test's headers to `DefaultHttpHeader` instance itself, then construct a `Netty4HeadersAdapter` out of it, tests fail again despite your changes:
> 
> ```java
> 	@Test
> 	void prepopulatedNativeNetty4() {
> 		DefaultHttpHeaders native = new DefaultHttpHeaders();
> 		native.add("TestHeader", "first");
> 		native.add("TestHEADER", "second");
> 		native.add("SecondHeader", "value");
> 		native.add("TestHeader", "third");
> 
> 		MultiValueMap<String, String> adapter = new Netty4HeadersAdapter(native);
> 
> 		//copying native headers into a new HttpHeaders
> 		HttpHeaders headers = new HttpHeaders();
> 		for (Map.Entry<String, List<String>> entry : adapter.entrySet()) {
> 			headers.addAll(entry.getKey(), entry.getValue());
> 		}
> 
> 		assertThat(headers.get("TestHeader")).as("TestHeader")
> 				.containsExactly("first", "second", "third");
> 	}
> ```

@simonbasle Indeed, perhaps it is necessary to reset it during the Adapter initialization.

2024-10-30 17:31 UTC, simonbasle commented
Superseded by gh-33823

2024-10-30 17:31 UTC, closed without merging