Added example how to use JsonUnit
spring-projects/spring-framework pull request #33953
Opened 2024-11-24 19:36 UTC by lukas-krecan

Added example how to use JsonUnit.

2024-11-24 19:36 UTC, lukas-krecan commented
I am not sure if I am supposed to add the example to Spring test or what's expected. Feel free to send suggenstions.

2024-11-26 19:13 UTC, snicoll requested changes
I've added a couple of comments.

2024-11-26 19:13 UTC, snicoll commented on framework-docs/modules/ROOT/pages/testing/mockmvc/assertj/assertions.adoc
> +Alternatively, you can use AssertJ https://github.com/assertj/assertj/blob/3.x/assertj-core/src/main/java/org/assertj/core/api/AssertFactory.java[AssertFactory].
Please rephrase that to be consistent with previous sentences. For instance.

JsonUnit is also supported via the standard `convertTo`method. I am not keen to start referring to AssertJ's Javadoc for this.

2024-11-26 19:13 UTC, snicoll commented on framework-docs/modules/ROOT/pages/testing/mockmvc/assertj/assertions.adoc
> +import static net.javacrumbs.jsonunit.assertj.JsonAssertions.jsonUnitJson;
This isn't markdown. We don't compile against JSonUnit so we can't add the example.

2024-12-06 08:45 UTC, snicoll commented
Closing due to the lack of feedback.

2024-12-06 08:45 UTC, closed without merging