Y_Update PlaceholderParser.java
spring-projects/spring-framework pull request #34021
Opened 2024-12-04 13:25 UTC by abdelmawla56

i have solved the NestedPlaceholderPart does not recursively resolve placeholders #34020 issue

2024-12-04 13:25 UTC, pivotal-cla commented
@abdelmawla56 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=34021)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=34021) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-12-04 13:29 UTC, abdelmawla56 commented
hello @vip-delete @spring-projects i have solved the issue please allow me to edit the file

2024-12-04 13:54 UTC, snicoll requested changes
Thanks for he PR

> i have solved the issue please allow me to edit the file

I am not sure what you're asking.

Can you please review the note and add a unit test that shows the use case described in the issue?

2024-12-04 13:54 UTC, snicoll commented on spring-core/src/main/java/org/springframework/util/PlaceholderParser.java
> -			String resolvedValue = resolveToText(resolutionContext, this.key);
Please revert all the formatting change as it makes it harder for us to see what you've changed.

2024-12-05 15:23 UTC, snicoll commented
Looking at the code I am not sure what that meant to accomplish. If you want to contribute, please create a proper branch so that you can work in your IDE and add some tests. I've taken over, see #34020

2024-12-05 15:23 UTC, closed without merging