SPR-13657 Buffered AsyncClientHttpResponse
spring-projects/spring-framework pull request #915
Opened 2015-11-08 18:53 UTC by jmnarloch

This pull request relates to https://github.com/spring-projects/spring-framework/pull/912 in a way that it covers some additional use cases that could be covered through AsyncRestTemplate like for instance request/response logging. To fully facilitate that you would require the responses to be buffered.

2017-02-21 22:16 UTC, Vijendra07Kulhade requested changes
Are these changes going in some release? I am looking for the solution for my question http://stackoverflow.com/questions/42309192/how-to-use-bufferingclienthttpresponsewrapper-with-httpcomponentsasyncclienthttp

2017-02-22 19:03 UTC, Vijendra07Kulhade commented
I tried using these changes with `AsyncRestTemplate`. `BufferingAsyncClientHttpRequestFactory` is only implementing `AsyncClientHttpRequestFactory` and `AsyncRestTemplate` constructor takes `ClientHttpRequestFactory` also. It will break during autowiring.

2018-02-03 01:03 UTC, oalmali commented
This is really needed why this PR is abandoned?

2018-02-05 14:10 UTC, rstoyanchev commented
I'm not sure how this one slipped through but the `AsyncRestTemplate` is deprecated in 5.0 in favor of `WebClient`, and we're not planning any more new features in 4.3.x. If you're on 5.0, I would highly recommend using the `WebClient` instead.

2018-02-05 14:10 UTC, closed without merging

2018-02-05 14:10 UTC, pivotal-issuemaster commented
@jmnarloch Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-framework&pullRequestId=915)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-framework&pullRequestId=915) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.